"""Add User

Revision ID: c3e24b42d180
Revises: ba177558f82d
Create Date: 2026-02-20 17:51:45.294704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e24b42d180'
down_revision = 'ba177558f82d'
branch_labels = None
depends_on = None


def upgrade():
   pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
